stages:
  - deploy

image: ${DOCKER_DEPLOY_IMAGE_NAME}:${DOCKER_DEPLOY_IMAGE_TAG}

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  STACK: kafka-utils
  KADMIN_VERSION: latest

deploy-kadmin-supporting-branch-develop:
  stage: deploy
  variables:
    SSH_REMOTE: ${DEV_SSH_REMOTE}
    SERVICES_TO_CHECK: ${STACK}_${CI_PROJECT_NAME}
    IMAGE_TAG: ${KADMIN_VERSION}
    COMPOSE_FILE: docker-compose.${CI_PROJECT_NAME}.tmpl.yml:docker-compose.${CI_PROJECT_NAME}.dev.yml
    PUBLIC_HOSTNAME: ${DEV_PUBLIC_HOSTNAME}
    UI_AUTH: ${DEV_UI_AUTH}
  script:
    - >
      deploy.sh IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE} PUBLIC_HOSTNAME=${PUBLIC_HOSTNAME}
      UI_AUTH=${UI_AUTH}
  environment:
    name: dev/${CI_PROJECT_NAME}
  only:
    - branches
  except:
    - master
  when: manual

deploy-kadmin-stable-branch-develop:
  stage: deploy
  variables:
    SSH_REMOTE: ${DEV_SSH_REMOTE}
    SERVICES_TO_CHECK: ${STACK}_${CI_PROJECT_NAME}
    IMAGE_TAG: ${KADMIN_VERSION}
    COMPOSE_FILE: docker-compose.${CI_PROJECT_NAME}.tmpl.yml:docker-compose.${CI_PROJECT_NAME}.dev.yml
    PUBLIC_HOSTNAME: ${DEV_PUBLIC_HOSTNAME}
    UI_AUTH: ${DEV_UI_AUTH}
  script:
     - >
      deploy.sh IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE} PUBLIC_HOSTNAME=${PUBLIC_HOSTNAME}
      UI_AUTH=${UI_AUTH}
  environment:
    name: dev/${CI_PROJECT_NAME}
  only:
    - master
  when: manual

deploy-kadmin-supporting-branch-production:
  stage: deploy
  variables:
    SSH_REMOTE: ${PRO_SSH_REMOTE}
    SERVICES_TO_CHECK: ${STACK}_${CI_PROJECT_NAME}
    IMAGE_TAG: ${KADMIN_VERSION}
    COMPOSE_FILE: docker-compose.${CI_PROJECT_NAME}.tmpl.yml:docker-compose.${CI_PROJECT_NAME}.prod.yml
    PUBLIC_HOSTNAME: ${DEV_PUBLIC_HOSTNAME}
    UI_AUTH: ${DEV_UI_AUTH}
  script:
     - >
      deploy.sh IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE} PUBLIC_HOSTNAME=${PUBLIC_HOSTNAME}
      UI_AUTH=${UI_AUTH}
  environment:
    name: pro/${CI_PROJECT_NAME}
  only:
    - branches
  except:
    - master
  when: manual

deploy-kadmin-stable-branch-production:
  stage: deploy
  variables:
    SSH_REMOTE: ${PRO_SSH_REMOTE}
    SERVICES_TO_CHECK: ${STACK}_${CI_PROJECT_NAME}
    IMAGE_TAG: ${KADMIN_VERSION}
    COMPOSE_FILE: docker-compose.${CI_PROJECT_NAME}.tmpl.yml:docker-compose.${CI_PROJECT_NAME}.prod.yml
    PUBLIC_HOSTNAME: ${DEV_PUBLIC_HOSTNAME}
    UI_AUTH: ${DEV_UI_AUTH}
  script:
     - >
      deploy.sh IMAGE_TAG=${IMAGE_TAG} COMPOSE_FILE=${COMPOSE_FILE} PUBLIC_HOSTNAME=${PUBLIC_HOSTNAME}
      UI_AUTH=${UI_AUTH}
  environment:
    name: pro/${CI_PROJECT_NAME}
  only:
    - master
  when: manual
