version: '3.5'

services:
  kadmin:
    image: ${IMAGE_NAME:-bettercloud/kadmin}:${IMAGE_TAG:-latest}
    environment:
      ZOOKEEPER_HOST: zk-1:${ZK_PORT},zk-2:${ZK_PORT},zk-3:${ZK_PORT}
      KAFKA_HOST: kf-1:${KF_PORT},kf-2:${KF_PORT},kf-3:${KF_PORT}
      SCHEMA_REGISTRY_URL: http://schema-registry:${SR_PORT}
      SECURITY_PROTOCOL: PLAINTEXT
      TRUST_STORE_LOCATION: ssl/client.truststore.jks
      TRUST_STORE_PASSWORD: password
      KEY_STORE_LOCATION: ssl/server.keystore.jks
      KEY_STORE_PASSWORD: password
      KEY_PASSWORD: password
      FF_PRODUCER_ENABLED: ${FF_PRODUCER_ENABLED}
    networks:
      - kafka-net
      - traefik-net
    healthcheck:
      test: curl --silent --output /dev/null http://localhost:${KADMIN_PORT}
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 2m
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.frontend.auth.basic.users: ${UI_AUTH}
        traefik.frontend.rule: Host:kadmin.${PUBLIC_HOSTNAME};ReplacePathRegex:^/$$ /kadmin/
        traefik.backend: kadmin
        traefik.port: '${KADMIN_PORT}'
      restart_policy:
        delay: 30s
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          memory: 256M

networks:
  kafka-net:
    name: ${KAFKA_NET_NAME:-kafka-net}
    external: true

  traefik-net:
    name: ${TRAEFIK_NET_NAME:-traefik-net}
    external: true